# Due to a limitation in Mintmaker, we need to create a dummy Dockerfile that does not use ARGs
# This should match the RUNTIME_IMAGE in container_build_args.conf
# Mintmaker should keep these in sync automatically when it performs updates
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:fe9e574f04371b333ed4e21d30d984f6b7fcd1046e579f5ddab4816c0c8e231d
#
