# Due to a limitation in Mintmaker, we need to create a dummy Dockerfile that does not use ARGs
# This should match the BUILDER_IMAGE in container_build_args.conf
# Mintmaker should keep these in sync automatically when it performs updates
FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:2323fcffe84ab72fa11b611be567d8a1bc6f83d3ed3a80327b18399258ea9aa6
#
