# Due to a limitation in Mintmaker, we need to create a dummy Dockerfile that does not use ARGs
# This should match the BUILDER_IMAGE in container_build_args.conf
# Mintmaker should keep these in sync automatically when it performs updates
FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:7a38d75d376f7989033e75fcaaf9fcbb090fafc58e05c2c99de76ae0ba083fdb
#
