//! Shared helpers for unit tests that need real key material generated by openssl.

use std::{
    io::Write,
    process::{Command, Stdio},
};

pub(crate) fn generate_ed25519_pkcs8_pem() -> Vec<u8> {
    let output = Command::new("openssl")
        .args(["genpkey", "-algorithm", "Ed25519"])
        .output()
        .expect("failed to generate Ed25519 key");
    assert!(output.status.success(), "openssl genpkey Ed25519 failed");
    output.stdout
}

pub(crate) fn generate_ec_pkcs8_pem(curve: &str) -> Vec<u8> {
    let ecparam = Command::new("openssl")
        .args(["ecparam", "-name", curve, "-genkey", "-noout"])
        .output()
        .expect("failed to generate EC key");
    assert!(ecparam.status.success(), "ecparam failed");

    let mut child = Command::new("openssl")
        .args(["pkcs8", "-topk8", "-nocrypt"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to spawn openssl pkcs8");

    child.stdin.take().unwrap().write_all(&ecparam.stdout).unwrap();

    let output = child.wait_with_output().expect("pkcs8 conversion failed");
    assert!(
        output.status.success(),
        "pkcs8 conversion failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    output.stdout
}
