# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile the code
# This should match the dummy file Dockerfile.mintmaker in the lock-build directory
# Mintmaker should keep these in sync automatically when it performs updates
BUILDER_IMAGE=registry.access.redhat.com/ubi9/ubi:latest@sha256:2323fcffe84ab72fa11b611be567d8a1bc6f83d3ed3a80327b18399258ea9aa6
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:12db9874bd753eb98b1ab3d840e75de5d6842ac0604fbd68c012adefe97140be
#
