# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile the code
# This should match the dummy file Dockerfile.mintmaker in the lock-build directory
# Mintmaker should keep these in sync automatically when it performs updates
BUILDER_IMAGE=registry.access.redhat.com/ubi9/ubi:latest@sha256:aecc1f893388841178ce0276e2f7b087e63e1e4521ec86a96d9c9416c6d419fa
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:17fd831ced9434de0a984d60b3fbe61008308261ba98bbc348d6fbdef05fa7c0
#
