# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile the code
# This should match the dummy file Dockerfile.mintmaker in the lock-build directory
# Mintmaker should keep these in sync automatically when it performs updates
BUILDER_IMAGE=registry.access.redhat.com/ubi9/ubi:latest@sha256:157ac93fde9596b9e04908fa9a22746350f53452718af9562289239f68a505c6
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:1bc3c5c15720506a0cf48adfdf8b623dfe704377e007d7bbae8d14876392ca6a
#
