---
jobs:
  build:
    name: Rust (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-26.04, ubuntu-24.04-arm, ubuntu-26.04-arm]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run rust-ci job
        run: make rust-ci
name: Rust
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
